language: objective-c

branches:
  only:
  - master
  
xcode_project: SwipyCell.xcodeproj
xcode_scheme: SwipyCell
osx_image: xcode8
xcode_sdk: iphonesimulator10.0

script:
- pod lib lint
- xctool -project SwipyCell.xcodeproj -scheme SwipyCell clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
