language: swift
osx_image: xcode12

branches:
  only:
    - main

before_install:
  - gem update cocoapods

script:
- swift build -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios14.0-simulator"
- pod lib lint
